language: php

env:
  global:
    - XDEBUG_MODE=coverage

matrix:
  include:
    - php: 7.3
    - php: 7.4
    - php: 8.0

before_script:
  - mkdir -p build/logs
  - travis_retry composer install --prefer-source --no-interaction
  - composer dump-autoload -o

script:
  - composer cs-check
  - bin/phpstan analyse src/ --level=max
  - bin/kahlan --coverage=4 --reporter=verbose --clover=build/logs/clover.xml
  - bin/php-coveralls -v --exclude-no-stmt

notifications:
    email: false
