language: php

matrix:
  include:
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=latest
    - php: 7.2
      env:
        - DEPS=lowest
    - php: 7.2
      env:
        - DEPS=latest
    - php: 7.3
      env:
        - DEPS=lowest
    - php: 7.3
      env:
        - DEPS=latest
    - php: 7.4
      env:
        - DEPS=lowest
    - php: 7.4
      env:
        - DEPS=latest

before_script:
  - mkdir -p build/logs
  - if [[ $DEPS == 'lowest' ]]; then travis_retry php ./composer.phar update --prefer-lowest --prefer-stable --no-interaction ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry php ./composer.phar install --prefer-source --no-interaction ; fi
  - php ./composer.phar dump-autoload -o

script:
  - if [[ $DEPS == 'latest' ]]; then php ./composer.phar cs-check ; fi
  - bin/phpstan analyse src/ --level=max
  - bin/kahlan --coverage=4 --reporter=verbose --clover=build/logs/clover.xml
  - bin/php-coveralls -v --exclude-no-stmt

notifications:
    email: false
