name: "ci build"

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  build:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.3', '7.4', '8.0']
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.0
        with:
          extensions: intl
          php-version: "${{ matrix.php-versions }}"
          coverage: xdebug
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Validate composer.json and composer.lock"
        run: "composer validate"
      - if: matrix.php-versions != '8.0'
        name: "Install dependencies"
        run: "composer install"
      - if: matrix.php-versions == '8.0'
        name: "Install dependencies"
        run: "composer install --ignore-platform-reqs"
      - name: "Run test suite"
        run: "mkdir -p build/logs && bin/kahlan --coverage=4 --reporter=verbose --clover=build/logs/coverage.xml && bin/php-coveralls -v --exclude-no-stmt"
        env:
          XDEBUG_MODE: "coverage"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/logs/coverage.xml
          flags: tests
          name: codecov-umbrella
          yml: ./codecov.yml
          fail_ci_if_error: true