name: "ci build"

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  build:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.0', '8.1']
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@v2
        with:
          extensions: intl
          php-version: "${{ matrix.php-versions }}"
          coverage: xdebug
      - name: Checkout
        uses: actions/checkout@v2
      - run: "composer validate"
      - name: "Install dependencies"
        run: "composer install --prefer-dist"
      - name: "CS Check"
        run: "composer cs-check"
      - name: "Code analyze"
        run: |
          bin/phpstan analyse src/ --level=8 -c phpstan.neon
          bin/rector process --dry-run
      - name: "Run test suite"
        run: "mkdir -p build/logs && bin/kahlan --coverage=4 --reporter=verbose --clover=build/logs/clover.xml"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/logs/clover.xml
          flags: tests
          name: codecov-umbrella
          yml: ./codecov.yml
          fail_ci_if_error: true
